---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: tetrataenite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP
platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: os-release
    properties:
      ID: fedora
      ID_LIKE: fedora
      NAME: tetrataenite
      PRETTY_NAME: tetrataenite

  - type: dnf
    repos:
      copr:
        - secureblue/packages
      files:
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://repo.secureblue.dev/secureblue.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - vscode.repo
        - google-chrome.repo
    install:
      install-weak-deps: false
      packages:
        - adw-gtk3-theme
        - bazaar
        - code
        - distrobox
        - gnome-tweaks
        - google-chrome-stable
        - tetrataenite-logos-0.0.1-1.fc43.x86_64.rpm
        - ms-core-fonts
        - mullvad-vpn
        - trivalent
        - vim
    remove:
      packages:
        - epiphany-runtime
        - fedora-chromium-config
        - fedora-chromium-config-gnome
        - fedora-flathub-remote
        - fedora-third-party
        - fedora-workstation-repositories
        - firefox
        - firefox-langpacks
        - gnome-remote-desktop
        - gnome-shell-extension-background-logo
        - gnome-software
        - gnome-tour
        - totem-video-thumbnailer

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "chmod +x /usr/bin/google-chrome"
      - "chmod +x /usr/bin/google-chrome-stable"

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: Flathub (system)
        install:
          - com.github.tchx84.Flatseal

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - 307 # Dash-to-Dock

  - type: gschema-overrides
    include:
      - zz1-tetrataenite.gschema.override
  
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - NerdFontsSymbolsOnly

  - type: brew
    nofile-limits: true
    brew-analytics: false
    auto-update: true
    auto-upgrade: true

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully