assign [app_id="chromium-browser"] workspace 2
assign [app_id="codium"] workspace 3
assign [app_id="nheko"] workspace 4
assign [app_id="calibre-gui"] workspace 5
assign [app_id="org.qbittorrent.qBittorrent"] workspace 8
assign [app_id="org.keepassxc.KeePassXC"] workspace 8
