assign [app_id="chromium-browser"] workspace 2
assign [app_id="google-chrome"] workspace 2
assign [app_id="trivalent"] workspace 2
assign [app_id="codium"] workspace 3
assign [app_id="org.gnome.gitlab.somas.Apostrophe"] workspace 3
assign [app_id="nheko"] workspace 4
assign [app_id="org.gnome.Fractal"] workspace 4
assign [app_id="org.gajim.Gajim"] workspace 4
assign [app_id="calibre-gui"] workspace 5
assign [app_id="org.kde.okular"] workspace 5
assign [app_id="org.qbittorrent.qBittorrent"] workspace 8
assign [app_id="org.keepassxc.KeePassXC"] workspace 8
assign [app_id="Mullvad VPN"] workspace 8
